/mob/carbon/New()
	spawn (1)
		src.organs += new /atom/organ("chest")
		src.organs += new /atom/organ("diaper")
		src.organs += new /atom/organ("head")
		src.organs += new /atom/organ("l_arm")
		src.organs += new /atom/organ("r_arm")
		src.organs += new /atom/organ("l_hand")
		src.organs += new /atom/organ("r_hand")
		src.organs += new /atom/organ("l_leg")
		src.organs += new /atom/organ("r_leg")
		src.organs += new /atom/organ("l_foot")
		src.organs += new /atom/organ("r_foot")