/mob/carbon/human
	name = "human"
	icon = 'mob.dmi'
	icon_state = "m-none"
	var/occupation1 = "No Preference"
	var/occupation2 = "No Preference"
	var/occupation3 = "No Preference"
	var/need_gl = 0.0
	var/be_epil = 0.0
	var/be_cough = 0.0
	var/be_tur = 0.0
	var/be_stut = 0.0
	var/r_hair = 0.0
	var/g_hair = 0.0
	var/b_hair = 0.0
	var/h_style = "Short Hair (M)"
	var/nr_hair = 0.0
	var/ng_hair = 0.0
	var/nb_hair = 0.0
	var/ns_tone = 0.0
	var/r_eyes = 0.0
	var/g_eyes = 0.0
	var/b_eyes = 0.0
	var/s_tone = 0.0
	var/age = 30.0
	var/b_type = "A+"
	var/obj/item/weapon/clothing/suit/wear_suit = null
	var/obj/item/weapon/clothing/under/w_uniform = null
	var/obj/item/weapon/radio/w_radio = null
	var/obj/item/weapon/clothing/shoes/shoes = null
	var/obj/item/weapon/belt = null
	var/obj/item/weapon/clothing/gloves/gloves = null
	var/obj/item/weapon/clothing/glasses/glasses = null
	var/obj/item/weapon/clothing/head/head = null
	var/obj/item/weapon/clothing/ears/ears = null
	var/obj/item/weapon/card/id/wear_id = null
	var/obj/item/weapon/r_store = null
	var/obj/item/weapon/l_store = null
	var/icon/stand_icon = null
	var/icon/lying_icon = null
	var/now_pushing = null
	var/t_plasma = 0.0
	var/t_oxygen = 0.0
	var/last_b_state = 1.0
	var/image/face = null
	var/image/face2 = null
	var/h_style_r = "hair_a"
	weight = 2500000.0
	var/cameraFollow = null

	var/list/body_standing = list()
	var/list/body_lying = list()
	var/list/organs = list()