/mob/Topic(href, href_list)
	if (href_list["mach_close"])
		src.machine = null
		ss13_browse(src, null, "window=[href_list["mach_close"]]")
	else if(href_list["priv_msg"])
		usr.client.private_message(src)
	else if(href_list["freeze"])
		var/mob/M = locate(href_list["freeze"])
		if(M)
			usr.client.toggle_frozen(M)
	else if(href_list["vote"])
		src.vote()
	return ..()