

/world/New()

	..()
	spawn( 0 )
		SetupOccupationsList()
		return
	return

/mob/prespawn/proc/Assign_Rank(rank, joined_late)
	var/startloc = null
	if(!joined_late)
		var/obj/S = locate("start*[rank]")
		if ((istype(S, /obj/start) && istype(S.loc, /turf) && !( ctf )))
			startloc = S.loc

	if (rank == "AI")
		var/mob/silicon/ai/A = new()
		A.loc = startloc
		A.client = src.client
		del(src)
		return

	var/mob/carbon/M = new(startloc)

	M.equip_if_possible(new /obj/item/weapon/radio/headset(M), M.SLOT_HEADSET)
	M.equip_if_possible(new /obj/item/weapon/storage/backpack(M), M.SLOT_BACK)
	switch(rank)
		if("Research Assistant")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/labcoat(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clipboard(M), M.SLOT_L_HAND)
		if("Technical Assistant")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/yellow(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/orange(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/storage/toolbox(M), M.SLOT_L_HAND)
			M.equip_if_possible(new /obj/item/weapon/crowbar(M), M.SLOT_IN_BACKPACK)
		if("Staff Assistant")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/red(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/handcuffs(M), M.SLOT_L_HAND)
		if("Medical Assistant")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/labcoat(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/storage/firstaid/regular(M), M.SLOT_L_HAND)
		if("Engineer")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/yellow(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/orange(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/storage/toolbox(M), M.SLOT_L_HAND)
			M.equip_if_possible(new /obj/item/weapon/crowbar(M), M.SLOT_IN_BACKPACK)
		if("Research Technician")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/labcoat(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clipboard(M), M.SLOT_L_HAND)
		if("Forensic Technician")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/red(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/gloves/latex(M), M.SLOT_GLOVES)
			M.equip_if_possible(new /obj/item/weapon/storage/fcard_kit(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/fcardholder(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/f_print_scanner(M), M.SLOT_IN_BACKPACK)
		if("Medical Doctor")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/labcoat(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/storage/firstaid/regular(M), M.SLOT_L_HAND)
		if("Captain")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/darkgreen(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/armor(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/head/swat_hel(M), M.SLOT_HELMET)
			M.equip_if_possible(new /obj/item/weapon/clothing/glasses/sunglasses(M), M.SLOT_GLASSES)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/taser_gun(M), M.SLOT_BELT)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/laser_gun(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/storage/id_kit(M), M.SLOT_IN_BACKPACK)
		if("Security Officer")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/red(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/armor(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/head/helmet(M), M.SLOT_HELMET)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/glasses/sunglasses(M), M.SLOT_GLASSES)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/taser_gun(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/handcuffs(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/handcuffs(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/storage/flashbang_kit(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/baton(M), M.SLOT_BELT)
			M.equip_if_possible(new /obj/item/weapon/flash(M), M.SLOT_L_STORE)
		if("Genetic Researcher")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/labcoat(M), M.SLOT_SUIT)
		if("Toxin Researcher")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/white(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/white(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/bio_suit(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/head/bio_hood(M), M.SLOT_HELMET)
			M.equip_if_possible(new /obj/item/weapon/clothing/mask/gasmask(M), M.SLOT_MASK)
			M.equip_if_possible(new /obj/item/weapon/tank/oxygentank(M), M.SLOT_L_HAND)
		if("Head of Research")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/green(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/armor(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/head/helmet(M), M.SLOT_HELMET)
			M.equip_if_possible(new /obj/item/weapon/clothing/glasses/sunglasses(M), M.SLOT_GLASSES)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/taser_gun(M), M.SLOT_BELT)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/laser_gun(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/storage/id_kit(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/flash(M), M.SLOT_L_STORE)
		if("Head of Personnel")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/green(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/suit/armor(M), M.SLOT_SUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/brown(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/clothing/head/helmet(M), M.SLOT_HELMET)
			M.equip_if_possible(new /obj/item/weapon/clothing/glasses/sunglasses(M), M.SLOT_GLASSES)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/taser_gun(M), M.SLOT_BELT)
			M.equip_if_possible(new /obj/item/weapon/gun/energy/laser_gun(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/storage/id_kit(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/flash(M), M.SLOT_L_STORE)
		if("Station Technician")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/yellow(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/orange(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/storage/toolbox(M), M.SLOT_L_HAND)
			M.equip_if_possible(new /obj/item/weapon/crowbar(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/cable_coil(M), M.SLOT_IN_BACKPACK)
			M.equip_if_possible(new /obj/item/weapon/t_scanner(M), M.SLOT_BELT)
		if("Atmospheric Technician")
			M.equip_if_possible(new /obj/item/weapon/clothing/under/yellow(M), M.SLOT_JUMPSUIT)
			M.equip_if_possible(new /obj/item/weapon/clothing/shoes/orange(M), M.SLOT_SHOES)
			M.equip_if_possible(new /obj/item/weapon/storage/toolbox(M), M.SLOT_L_HAND)
			M.equip_if_possible(new /obj/item/weapon/crowbar(M), M.SLOT_IN_BACKPACK)
		else
			//this shouldn't ever happen?
			M << "UH OH! Your job is [rank] and the game just can't handle it! Please report this bug to an administrator."

	var/obj/item/weapon/card/id/C = new /obj/item/weapon/card/id(M)
	C.registered = M.spawn_name
	C.assignment = rank
	C.name = "[C.registered]'s ID Card ([C.assignment])"
	C.access = get_access(C.assignment)
	M.equip_if_possible(C, M.SLOT_ID)
	M.equip_if_possible(new /obj/item/weapon/pen(M), M.SLOT_R_STORE)
	M.equip_if_possible(new /obj/item/weapon/radio/signaler(M), M.SLOT_BELT)

	if(rank == "Captain")
		world << "<b>[M] is the captain!</b>"
	src << "<B>You are the [rank].</B>"

	M.client = src.client
	del(src)

/proc/AutoUpdateAI(obj/subject)
	if (subject!=null)
		for(var/mob/silicon/ai/M in world)
			if ((M.client && M.machine == subject))
				subject.interact(M)
