/mob/carbon
	var
		intent = null
		a_intent = "disarm"
		m_int = null
		m_intent = "run"
		obj/dna/dna = null
		sdisabilities = 0.0
		disabilities = 0.0
		atom/movable/pulling = null
		stat = 0.0
		next_move = null
		prev_move = null
		monkeyizing = null
		other = 0.0
		hand = null
		eye_blind = null
		eye_blurry = null
		ear_deaf = null
		ear_damage = null
		stuttering = null
		rname = null
		blinded = null
		rejuv = null
		r_epil = null
		r_ch_cou = null
		r_Tourette = null
		antitoxs = null
		plasma = null
		virus = 0.0
		sleeping = 0.0
		resting = 0.0
		lying = 0.0
		canmove = 1.0
		eye_stat = null
		timeofdeath = 0.0
		cpr_time = 1.0
		drowsyness = 0.0
		paralysis = 0.0
		stunned = 0.0
		weakened = 0.0
		losebreath = 0.0
		obj/stool/chair/buckled = null
		obj/item/weapon/handcuffs/handcuffed = null
		obj/item/weapon/l_hand = null
		obj/item/weapon/r_hand = null
		obj/item/weapon/back = null
		obj/item/weapon/tank/internal = null
		obj/item/weapon/storage/s_active = null
		obj/item/weapon/clothing/mask/mask = null
		obj/screen/flash = null
		obj/screen/blind = null
		obj/screen/hands = null
		obj/screen/mach = null
		obj/screen/sleep = null
		obj/screen/rest = null
		obj/screen/pullin = null
		obj/screen/internals = null
		obj/screen/oxygen = null
		obj/screen/i_select = null
		obj/screen/m_select = null
		obj/screen/toxin = null
		obj/screen/fire = null
		obj/screen/healths = null
		obj/screen/zone_sel/zone_sel = null
		obj/hud/hud_used = null
		grabbed_by = list()
		datum/chemical/chemicals = null

		const
			slot_back = 1
			slot_mask = 2
			slot_handcuffed = 3
			slot_l_hand = 4
			slot_r_hand = 5
			slot_belt = 6
			slot_id = 7
			slot_ears = 8
			slot_glasses = 9
			slot_gloves = 10
			slot_head = 11
			slot_shoes = 12
			slot_suit = 13
			slot_jumpsuit = 14
			slot_l_store = 15
			slot_r_store = 16
			slot_headset = 17
			slot_in_backpack = 18
	var/obj/item/weapon/clothing/suit/suit = null
	var/obj/item/weapon/clothing/under/jumpsuit = null
	var/obj/item/weapon/radio/headset = null
	var/obj/item/weapon/clothing/shoes/shoes = null
	var/obj/item/weapon/belt = null
	var/obj/item/weapon/clothing/gloves/gloves = null
	var/obj/item/weapon/clothing/glasses/glasses = null
	var/obj/item/weapon/clothing/head/head = null
	var/obj/item/weapon/clothing/ears/ears = null
	var/obj/item/weapon/card/id/id = null
	var/obj/item/weapon/r_store = null
	var/obj/item/weapon/l_store = null
	var/icon/stand_icon = null
	var/icon/lying_icon = null
	var/now_pushing = null
	var/t_plasma = 0.0
	var/t_oxygen = 0.0
	var/last_b_state = 1.0
	var/image/face = null
	var/image/face2 = null
	var/h_style_r = "hair_a"
	var/cameraFollow = null

	var/list/body_standing = list()
	var/list/body_lying = list()
	var/list/organs = list()

/mob/carbon/New()
	spawn (1)
		if (world.time < 60)
			sleep(7) //I guess this is here because of all the stuff taking forever to load? I won't mess with it.
		var/atom/organ/chest/chest = new /atom/organ/chest( src )
		chest.owner = src
		var/atom/organ/diaper/diaper = new /atom/organ/diaper( src )
		diaper.owner = src
		var/atom/organ/head/head = new /atom/organ/head( src )
		head.owner = src
		var/atom/organ/l_arm/l_arm = new /atom/organ/l_arm( src )
		l_arm.owner = src
		var/atom/organ/r_arm/r_arm = new /atom/organ/r_arm( src )
		r_arm.owner = src
		var/atom/organ/l_hand/l_hand = new /atom/organ/l_hand( src )
		l_hand.owner = src
		var/atom/organ/r_hand/r_hand = new /atom/organ/r_hand( src )
		r_hand.owner = src
		var/atom/organ/l_leg/l_leg = new /atom/organ/l_leg( src )
		l_leg.owner = src
		var/atom/organ/r_leg/r_leg = new /atom/organ/r_leg( src )
		r_leg.owner = src
		var/atom/organ/l_foot/l_foot = new /atom/organ/l_foot( src )
		l_foot.owner = src
		var/atom/organ/r_foot/r_foot = new /atom/organ/r_foot( src )
		r_foot.owner = src
		src.organs += chest
		src.organs += diaper
		src.organs += head
		src.organs += l_arm
		src.organs += r_arm
		src.organs += l_hand
		src.organs += r_hand
		src.organs += l_leg
		src.organs += r_leg
		src.organs += l_foot
		src.organs += r_foot